### ISSUE TITLE
More Windows issues after getting js-host working...

### ISSUE THREAD

**Issue by anyong** [markfinger/python-webpack#18]
I've looked at this one for a bit now as well and am currently stumped, here's the traceback...

```
Request Method: GET
Request URL:    http://127.0.0.1:8000/test
Django Version: 1.8.1
Exception Type: BundlingError
Exception Value:    
webpack: EntryModuleNotFoundError: Entry module not found: Error: Cannot resolve 'file' or 'directory' ./app.js in C:devprojectstaticsrcadminscripts
    at Tapable.<anonymous> (C:\dev\project\static\node_modules\webpack\lib\Compilation.js:346:28)
    at Tapable.<anonymous> (C:\dev\project\static\node_modules\webpack\lib\NormalModuleFactory.js:55:19)
    at C:\dev\project\static\node_modules\webpack\node_modules\async\lib\async.js:254:17
    at done (C:\dev\project\static\node_modules\webpack\node_modules\async\lib\async.js:129:15)
    at C:\dev\project\static\node_modules\webpack\node_modules\async\lib\async.js:32:16
    at C:\dev\project\static\node_modules\webpack\node_modules\async\lib\async.js:251:21
    at C:\dev\project\static\node_modules\webpack\node_modules\async\lib\async.js:575:34
    at C:\dev\project\static\node_modules\webpack\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:24:19
    at onResolved (C:\dev\project\static\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:38:18)
    at C:\dev\project\static\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:127:10
Exception Location: C:\Python34\lib\site-packages\js_host\function.py in send_request, line 92
Python Executable:  C:\Python34\python.exe
Python Version: 3.4.2
```

I guess it has something to do with the windows path backslashes...?

**Comment by markfinger** [comment]
Perhaps the `./` part of `./app.is` doesn't resolve on windows?

**Comment by anyong** [comment]
Ok, I found the source of this error. Python is removing the backslashes thinking they are escape characters, and webpack needs backslashes to resolve the paths. `./app.js` is not a problem. My solution is to convert Python's default backslash representation (a double backslash) into a double backslash (which is actually `\\\\`). I'm sure this is a really hacky way of doing it, but on react/bundle.py line 35 I added:

```
config = config.replace('\\', '\\\\')
```

That actually works, but now webpack is complaining that it I'm not loading babel-loader even though it's in the config (`translate=True`, and I've checked the automatically generated config file). I think the problem is probably related to what was going on [here](https://github.com/webpack/webpack-dev-server/issues/135), because I've got:

```
Connected to JSHostManager [127.0.0.1:9009]
Connected to JSHost [127.0.0.1:65423]
Starting development server at http://127.0.0.1:8000/
```

**Comment by markfinger** [comment]
Can you copy-paste one of the generated config files?

When I've previously had problems with using loaders in this way, it's usually been down to path issues. I think the config file should be pointing webpack at the node_modules dir for your project.

Might be worth checking what's happening in https://github.com/markfinger/python-react/blob/695cf0e8e4c9ca464037e027ff6bb4fc3f44c0c7/react/bundle.py#L58-L61 the key part being the output of https://github.com/markfinger/python-react/blob/695cf0e8e4c9ca464037e027ff6bb4fc3f44c0c7/react/templates.py#L36-L38

**Comment by anyong** [comment]
Here's one:

``` js
module.exports = {
    context: 'C:\\dev\\project\\static\\src\\admin\\scripts',
    entry: './app.js',
    output: {
        path: '[bundle_dir]/react-components',
        filename: 'scripts__app-[hash].js',
        libraryTarget: 'umd',
        library: 'scripts__app'
    },
    externals: [{
      react: {
        commonjs2: 'C:\\dev\\project\\static\\node_modules\\react',
        root: 'React'
      },
      'react/addons': {
        commonjs2: 'C:\\dev\\project\\static\\node_modules\\react',
        root: 'React'
      }
    }],
    devtool: 'eval',
    module: {
        loaders: [{
            test: /\\.jsx?$/, // I added the 'x?' in the template to transform both js/jsx files.
            exclude: /node_modules/,
            loader: 'babel-loader'
        }]
    },
    resolveLoader: {
        root: 'C:\\dev\\project\\static\\node_modules'
    }

};
```

**Comment by markfinger** [comment]
Could you try the latest release - 0.13.0 - and see if that fixes the issue?

Rather than dealing with string encoding issues, I've changed it use Node's `path` module. The config generated from the example now looks something like:

``` javascript
var path = require("path");
module.exports = {
  "context": path.join.apply(path, ["/", "Users", "markfinger", "Projects", "python-react", "example", "static", "jsx"]),
  "entry": "./CommentBox.jsx",
  "externals": [
    {
      "react": {
        "commonjs2": path.join.apply(path, ["/", "Users", "markfinger", "Projects", "python-react", "example", "node_modules", "react"]),
        "root": "React"
      },
      "react/addons": {
        "commonjs2": path.join.apply(path, ["/", "Users", "markfinger", "Projects", "python-react", "example", "node_modules", "react"]),
        "root": "React"
      }
    }
  ],
  "module": {
    "loaders": [
      {
        "exclude": /node_modules/,
        "loader": "babel-loader",
        "test": /.jsx$/
      }
    ]
  },
  "output": {
    "filename": "jsx__CommentBox-[hash].js",
    "library": "jsx__CommentBox",
    "libraryTarget": "umd",
    "path": "[bundle_dir]/react-components"
  },
  "resolveLoader": {
    "root": path.join.apply(path, ["/", "Users", "markfinger", "Projects", "python-react", "example", "node_modules"])
  }
};
```

Also, if you want to change the loader test, I've added a `TRANSLATE_TEST` setting. If not defined, it defaults to `'/.jsx$/'`

**Comment by anyong** [comment]
I reinstalled and am getting even more confusing errors than before...
definitely does not work on my computer at this stage.

Stacktrace:

```
"C:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.1.2\bin\runnerw.exe"
C:\Python34\python.exe C:/dev/project/manage.py runserver 8000
Traceback (most recent call last):
  File "C:/dev/project/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py",
line 338, in execute_from_command_line
    utility.execute()
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py",
line 312, in execute
    django.setup()
  File "C:\Python34\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python34\lib\site-packages\django\apps\registry.py", line 108,
in populate
    app_config.import_models(all_models)
  File "C:\Python34\lib\site-packages\django\apps\config.py", line 198, in
import_models
    self.models_module = import_module(models_module_name)
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in
_find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in
_call_with_frames_removed
  File "C:\Python34\lib\site-packages\js_host\models.py", line 7, in
<module>
    **getattr(settings, 'JS_HOST', {})
  File "C:\Python34\lib\site-packages\js_host\conf.py", line 55, in
configure
    from .host import host
  File "C:\Python34\lib\site-packages\js_host\host.py", line 8, in <module>
    manager = JSHostManager()
  File "C:\Python34\lib\site-packages\js_host\base_server.py", line 70, in
__init__
    self.validate_status()
  File "C:\Python34\lib\site-packages\js_host\base_server.py", line 214, in
validate_status
    version = self.get_version().split('.')
  File "C:\Python34\lib\site-packages\js_host\base_server.py", line 117, in
get_version
    return self.get_status()['version']
  File "C:\Python34\lib\site-packages\js_host\base_server.py", line 113, in
get_status
    self.status = self.read_config_file(self.get_path_to_config_file())
  File "C:\Python34\lib\site-packages\js_host\base_server.py", line 104, in
read_config_file
    raise ConfigError(stderr)
js_host.exceptions.ConfigError: b'Mon, 11 May 2015 16:27:16 GMT
express:application compile etag weak\nMon, 11 May 2015 16:27:16 GMT
express:application compile query parser extended\nMon, 11 May 2015
16:27:16 GMT express:application compile trust proxy false\nMon, 11 May
2015 16:27:16 GMT express:application booting in development mode\nMon, 11
May 2015 16:27:16 GMT express:router use / query\nMon, 11 May 2015 16:27:16
GMT express:router:layer new /\nMon, 11 May 2015 16:27:16 GMT
express:router use / expressInit\nMon, 11 May 2015 16:27:16 GMT
express:router:layer new /\nMon, 11 May 2015 16:27:16 GMT express:router
use / <anonymous>\nMon, 11 May 2015 16:27:16 GMT express:router:layer new
/\nMon, 11 May 2015 16:27:16 GMT express:router:route new /status\nMon, 11
May 2015 16:27:16 GMT express:router:layer new /status\nMon, 11 May 2015
16:27:16 GMT express:router:route get /status\nMon, 11 May 2015 16:27:16
GMT express:router:layer new /\nMon, 11 May 2015 16:27:16 GMT
express:router use / jsonParser\nMon, 11 May 2015 16:27:16 GMT
express:router:layer new /\nMon, 11 May 2015 16:27:16 GMT
express:router:route new /manager/stop\nMon, 11 May 2015 16:27:16 GMT
express:router:layer new /manager/stop\nMon, 11 May 2015 16:27:16 GMT
express:router:route post /manager/stop\nMon, 11 May 2015 16:27:16 GMT
express:router:layer new /\nMon, 11 May 2015 16:27:16 GMT express:router
use / <anonymous>\nMon, 11 May 2015 16:27:16 GMT express:router:layer new
/\nMon, 11 May 2015 16:27:16 GMT express:router:route new /host/start\nMon,
11 May 2015 16:27:16 GMT express:router:layer new /host/start\nMon, 11 May
2015 16:27:16 GMT express:router:route post /host/start\nMon, 11 May 2015
16:27:16 GMT express:router:layer new /\nMon, 11 May 2015 16:27:16 GMT
express:router:route new /host/stop\nMon, 11 May 2015 16:27:16 GMT
express:router:layer new /host/stop\nMon, 11 May 2015 16:27:16 GMT
express:router:route post /host/stop\nMon, 11 May 2015 16:27:16 GMT
express:router:layer new /\nMon, 11 May 2015 16:27:16 GMT
express:router:route new /host/restart\nMon, 11 May 2015 16:27:16 GMT
express:router:layer new /host/restart\nMon, 11 May 2015 16:27:16 GMT
express:router:route post /host/restart\nMon, 11 May 2015 16:27:16 GMT
express:router:layer new /\nMon, 11 May 2015 16:27:16 GMT
express:router:route new /host/status\nMon, 11 May 2015 16:27:16 GMT
express:router:layer new /host/status\nMon, 11 May 2015 16:27:16 GMT
express:router:route post /host/status\nMon, 11 May 2015 16:27:16 GMT
express:router:layer new /\nMon, 11 May 2015 16:27:16 GMT
express:router:route new /host/connect\nMon, 11 May 2015 16:27:16 GMT
express:router:layer new /host/connect\nMon, 11 May 2015 16:27:16 GMT
express:router:route post /host/connect\nMon, 11 May 2015 16:27:16 GMT
express:router:layer new /\nMon, 11 May 2015 16:27:16 GMT
express:router:route new /host/disconnect\nMon, 11 May 2015 16:27:16 GMT
express:router:layer new /host/disconnect\nMon, 11 May 2015 16:27:16 GMT
express:router:route post /host/disconnect\nMon, 11 May 2015 16:27:16 GMT
express:router:layer new /\n'

Process finished with exit code 1
```

**Comment by markfinger** [comment]
Hmm, I think I'll need to finish setting up the VM and start debugging this

**Comment by markfinger** [comment]
`development` branch decouples from js-host and uses a bespoke build server. Should minimise the scope for OS issues.

react's config generation is being removed, in favour of explicitly linked config files which are fed context. See: https://github.com/markfinger/python-react/issues/42

**Comment by markfinger** [comment]
Latest removes js-host dependency, with any luck that fixes the issues
