### ISSUE TITLE
Settings issue in Django 1.6

### ISSUE THREAD

**Issue by njoqi** [markfinger/python-webpack#35]
Hello there,

I'm using python-webpack in a django app, and settings don't seem to be passed.

In my settings : 

``` python
DJANGO_ROOT = dirname(dirname(abspath(__file__)))
# [...]
STATIC_ROOT = normpath(join(DJANGO_ROOT, '../media/static'))
STATIC_URL = '/media/static/'
# [...]
DEBUG = True
# [...]
########## WEBPACK
WEBPACK = {
    'STATIC_ROOT': STATIC_ROOT,
    'STATIC_URL': STATIC_URL,
    'WATCH': DEBUG,
    'HMR': DEBUG,
}
```

In my view : 

``` python
from webpack.compiler import webpack
# [...]
def some_view(request, arg):
    # [...]
    bundle=webpack('webpack.js')
```

And I'm getting :

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/vagrant/.venv/backend/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/home/vagrant/.venv/backend/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 206, in __call__
    response = self.get_response(request)
  File "/home/vagrant/.venv/backend/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 194, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/vagrant/.venv/backend/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/backend/frontend/views.py", line 77, in some_view
    bundle=webpack('webpack.js')
  File "/home/vagrant/.venv/backend/local/lib/python2.7/site-packages/webpack/compiler.py", line 22, in webpack
    setting_overrides=settings,
  File "/home/vagrant/.venv/backend/local/lib/python2.7/site-packages/webpack/build_server.py", line 25, in build
    setting_overrides=setting_overrides,
  File "/home/vagrant/.venv/backend/local/lib/python2.7/site-packages/webpack/options.py", line 17, in generate_compiler_options
    raise ImproperlyConfigured('webpack.conf.settings.STATIC_ROOT has not been defined.')
ImproperlyConfigured: webpack.conf.settings.STATIC_ROOT has not been defined.
```

**Comment by markfinger** [comment]
Is `'webpack'` in your `INSTALLED_APPS`?

**Comment by njoqi** [comment]
Yes :

``` python
INSTALLED_APPS = (
#[...]
    'react',
    'webpack',
)
```

**Comment by markfinger** [comment]
Strange.

Which version of django are you using?

**Comment by njoqi** [comment]
Version 1.6.8.
I'm using the 5.0.1 python-webpack (latest).

**Comment by markfinger** [comment]
Ah yeah, latest switched to 1.7's app config for the setup hook. You'll need to manually call the `webpack.conf.settings.configure` function.

After your `WEBPACK` dict in settings, add something like the following

``` python
# Forwards-compatible check for configuring webpack in Django < 1.7
import django
if django.VERSION[0] == 1 and django.VERSION[1] < 7:
    import webpack.conf
    webpack.conf.settings.configure(**WEBPACK)
```

**Comment by njoqi** [comment]
Yes, it's working now. Thanks for your help !
